repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.3.0'
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: requirements-txt-fixer
    -   id: check-added-large-files
        args: ['--maxkb=1024']

-   repo: https://github.com/psf/black
    rev: '22.6.0'
    hooks:
    - id: black
      args:
        - --line-length=100

-   repo: https://github.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
    -   id: flake8
        args:
            - --max-line-length=100
