# Generated by Django 4.1 on 2022-10-27 15:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=11)),
                ('title', models.CharField(max_length=256)),
                ('duration', models.SmallIntegerField()),
                ('published_at', models.DateField()),
                ('unique_words_in_lyrics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SongTextLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.SmallIntegerField()),
                ('text', models.CharField(max_length=128)),
                ('start_time', models.SmallIntegerField()),
                ('duration', models.SmallIntegerField()),
                ('language', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.language')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
        ),
    ]
