# Generated by Django 4.1 on 2022-10-27 18:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_alter_song_audio_file_download_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='unique_words_in_lyrics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
    ]
