# Generated by Django 4.1 on 2022-10-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_alter_song_unique_words_in_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.SmallIntegerField(default=0),
        ),
    ]
