# Generated by Django 4.1 on 2022-10-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_song_youtube_video_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_video_metadata',
            field=models.JSONField(default=dict),
        ),
    ]
