# Generated by Django 4.1 on 2022-10-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0015_alter_song_youtube_video_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default='...', max_length=256),
        ),
    ]
