# Generated by Django 4.1 on 2022-10-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0016_alter_song_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='unique_words_in_lyrics',
            new_name='raw_lyrics',
        ),
    ]
