# Generated by Django 4.1 on 2022-10-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0017_rename_unique_words_in_lyrics_song_raw_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='custom_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
