# Generated by Django 4.1 on 2022-10-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0018_song_custom_name_alter_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file_download_status',
            field=models.CharField(choices=[('0', 'Initial'), ('1', 'Processing'), ('2', 'Downloaded'), ('-1', 'Failed')], default='0', max_length=2),
        ),
    ]
