# Generated by Django 4.1 on 2022-10-28 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0020_alter_song_raw_lyrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songtextline',
            old_name='duration',
            new_name='duration_millisecond',
        ),
        migrations.RenameField(
            model_name='songtextline',
            old_name='start_time',
            new_name='start_time_millisecond',
        ),
    ]
