# Generated by Django 4.1 on 2022-10-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0021_rename_duration_songtextline_duration_millisecond_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songtextline',
            name='duration_millisecond',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='songtextline',
            name='start_time_millisecond',
            field=models.IntegerField(),
        ),
    ]
