# Generated by Django 4.1 on 2022-10-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0025_song_subtitles_download_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='subtitles_video_youtube_url',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
