# Generated by Django 4.1 on 2022-10-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0026_song_subtitles_video_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='subtitles_video_youtube_url',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
