# Generated by Django 4.1 on 2022-10-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0027_alter_song_subtitles_video_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='custom_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
