# Generated by Django 4.1 on 2022-10-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0028_alter_song_custom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songtextline',
            name='language',
        ),
        migrations.RemoveField(
            model_name='songtextline',
            name='song',
        ),
        migrations.RemoveConstraint(
            model_name='song',
            name='unique_song_from_youtube_per_user',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='subtitles_video_youtube_url',
            new_name='subtitles_source_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='raw_lyrics',
        ),
        migrations.RemoveField(
            model_name='song',
            name='subtitles_video_youtube_id',
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics_and_timings',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file_download_status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Processing', 'Processing'), ('Downloaded', 'Downloaded'), ('Failed', 'Failed')], default='Initial', max_length=16),
        ),
        migrations.AlterField(
            model_name='song',
            name='subtitles_download_status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Processing', 'Processing'), ('Downloaded', 'Downloaded'), ('Failed', 'Failed')], default='Initial', max_length=16),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='SongTextLine',
        ),
    ]
